demos/webpack.config.js
package.json
src/event-promo-client.js
src/main.js

es6 changes

---

main.scss
styles/_inarticle.scss
templates/inarticle.html

- Responsive images res
- Revised buttom size
- revise large to xl size layout

Style tweaks

---

src/event-promo-client.js
src/main.js

- raise useful errors rather than just re-throwing errors

improved error handling

---

demos/demo.html
demos/src/demo.js
main.scss
styles/_inarticle.scss

- Clean up tablet viewport styles and some typographic spacing

Style corrections

---

README.md

Update readme to existing implementation

---

styles/_inarticle.scss

reduced event-promo-inline__cta to 15px

---

src/lib/mapEventData.js
styles/_inarticle.scss
tests/fixtures/liveEvent.json

changed border color, move location to api

---

README.md
demos/src/demo.js
jest.config.js
src/main.js
templates/control.html
templates/variant.html
tests/main.spec.js

Just the logic for switching templates on flag value. 
No template styles here. Will be in separate PR

Ab variant template switching logic

---

demos/demo.html
demos/fixtures.json
main.scss
src/lib/mapEventData.js
styles/_inarticle-dark.scss
templates/control.html
templates/inarticle.html
templates/variant.html
tests/main.spec.js

Dark style template WIP

---

src/lib/mapEventData.js
templates/inarticle_dark.html
tests/lib/mapEventData.spec.js
tests/main.spec.js

-  variant boolean in query parm
- add data-trackable value to for cta events on the varaint

Pass variant flag

---

main.scss
styles/_inarticle-dark.scss
templates/inarticle_dark.html

Title layout fix

---

src/config.js

added missing slash

---

styles/_inarticle_dark.scss

correct z-index so less than stick headers

---

styles/_inarticle_light.scss

🐿 v2.10.2 small screen layout needed adjusting to match the darker version

correct small screen image sizes and overlap

---

templates/inarticle_dark.html
templates/inarticle_light.html

put the event-demo-varant on the right template

---

templates/inarticle_dark.html
templates/inarticle_light.html

🐿 v2.10.2 Sorts out the horrible ux of tabbing throught each image in the animation

remove dodgy tabbing on images

---

src/lib/mapEventData.js
src/main.js
templates/inarticle.html
tests/lib/mapEventData.spec.js
tests/main.spec.js

remove AB stuff

---

demos/src/demo.js
src/index.js
tests/lib/mapEventData.spec.js

🐿 v2.10.3 - still had some old AB stuff that is no longer used

remove redundent variant code

---

.circleci/config.yml
package.json
readme.md
src/ImagesContainer.jsx
test/ImagesContainer.spec.jsx
test/fixtures/eventpromoFixture.json
tooling/babel/index.js
tooling/jest/index.js

Previously the label read `control animation`. Without context it's not clear what this means, what does control mean and what animation does it refer to?
The new label will read 'Play "{title}" image slide show' for example 'Play "FT Brexit and Beyond Summit" image slideshow'.
I have chosen the word `slideshow` as I hope this is more descriptive of the animation.
If the animation is running it will say "Pause" instead of "Play".
In the future, I agree with the Digital Accessibility Center (DAC) report that we should reconsider this animation all together, could we remove it and keep a single fixed image?
DAC ID: IDAC_Non-Descriptive_Form_Elements_Issue4
See also: https://sarahmhigley.com/writing/playing-with-state/

Accessibility: Improve Image Slideshow button label

---

src/Details.jsx

Remove aria-labelledby attributes since they doesn't make sense there.
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?modal=detail&selectedIssue=CI-1465)

remove aria-labelledby since is not usefull in this case

---

package-lock.json
package.json

Fix for issue in circleci with publishing to npm:

updated version of @dotcom-tool-kit/npm

---

src/Eventpromo.jsx
src/Eventpromo.scss

Issue: [HIVE-1840](https://financialtimes.atlassian.net/browse/HIVE-1840)
Removed the explore all btn from the component
[HIVE-1840]: https://financialtimes.atlassian.net/browse/HIVE-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

removed the explore all events button
